<h2>About Us</h2>
<p>We have been in the business of stamp procurement and sales since
1927, and are internationally known for our expertise and industry-wide
Q: Why do none of the class definitions in this chapter include a closing PHP tag?
A: According to the Zend Framework coding standard, files that contain only PHP code should
not include the closing tag ?>, as it can lead to header problems with the HTTP response if
the text editor you’re using automatically adds a new line to the end of your files. For more
information on the Zend Framework coding standard, refer to the links at the end of this
chapter.
Ask the Expert
42 Zend Framework: A Beginner’s Guide
network. We encourage you to find out more about us using the links
above.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed
do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
enim ad minim veniam, quis nostrud exercitation ullamco laboris
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.</p>